---
title: "Paleomat Figures"
author: "Andrew Gillreath-Brown"
date: "08/29/2022"
output: bookdown::word_document2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(paleomat)
library(maps)
data(us.cities)
library(ggh4x)

```

# Figures

```{r fig1, fig.cap="Modern pollen samples used in this study from the Neotoma Paleoecological Database.", echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

MPCT_climate_final <-
  readr::read_rds(here::here("vignettes/data/MPCT_climate_final.rds"))

usa <-
  sf::st_as_sf(maps::map("state", fill = TRUE, plot = FALSE)) %>%
  sf::st_transform(., crs = 4326)

ggplot() +
  geom_sf(data = usa, fill = NA) +
  geom_sf(data = MPCT_climate_final,
          inherit.aes = FALSE,
          aes(geometry = geometry)) +
  coord_sf(xlim = c(-125, -95), ylim = c(25, 50)) +
  theme_classic() +
  scale_x_continuous(breaks = seq(-125, -95, 5.0)) +
  scale_y_continuous(breaks = seq(25, 50, 5)) +
  labs(colour = "") +
  theme(
    axis.ticks = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.text.x = element_text(angle = 90,
                               margin = margin(
                                 t = -25,
                                 r = 10,
                                 b = 10,
                                 l = 10
                               )),
    axis.line = element_blank()
  )

# ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/Figure1.png", dpi = 600)


```



```{r fig2, fig.cap="The Southwest United States (SWUS) as defined here, showing locations of fossil pollen samples used in this study. Background shading indicates mean July temperature for 1961 - 1990 from PRISM (Daly et al., 2008, 2015; PRISM Climate Group, 2019) at 800-m resolution. The solid gray box outlines the area studied by Bocinsky and Kohler (2014); the green dashed box shows the extent of the reconstruction in this study.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

# Showing extent of UUSS and the fossil pollen sites.

# Get locations of the fossil pollen sites.
fossil.locs <-
  readr::read_rds(here::here(
    "./vignettes/data/fossil_final_west_metadata_post5500BP.rds"
  )) %>%
  tidyr::extract(geometry, c('long', 'lat'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  dplyr::select(-geometry) %>%
  dplyr::group_by(site.name) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup() %>%
  dplyr::select(site.id, site.name, long, lat)

# Get the PRISM modern July temperature dataset.
temp.raster <-
  raster::raster("./vignettes/data/raw_data/temp.raster.tif")

# Create a bounding box for the upper united states southwest
bb <-
  c(
    "xmin" = -113,
    "xmax" = -105,
    "ymin" = 32,
    "ymax" = 38.09
  ) %>%
  sf::st_bbox() %>%
  sf::st_as_sfc() %>%
  sf::st_as_sf(crs = 4326) %>%
  sf::st_transform(crs = 4326)

cities2 <- us.cities %>%
  dplyr::select(name, long, lat) %>%
  dplyr::filter(
    name %in% c(
      "Farmington NM",
      "Santa Fe NM",
      "Albuquerque NM",
      "Flagstaff AZ",
      "Phoenix AZ"
    )
  ) %>%
  dplyr::add_row(name = "Mesa Verde CO",
                 long = -108.463050,
                 lat = 37.230299)

cities3 <- cities2
cities3$name <-
  trimws(gsub(
    pattern = "NM|AZ|CO",
    replacement = "",
    cities3$name,
    perl = T
  ))

cities <- cities2  %>%
  sf::st_as_sf(coords = c("long", "lat"), crs = 4326)

fossil.sites <- fossil.locs %>%
  sf::st_as_sf(coords = c("long", "lat"), crs = 4326)

crs(temp.raster) <-
  "+proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +ellps=GRS80 +datum=WGS84 +units=m +no_defs"
temperature <- as.data.frame(temp.raster, xy = TRUE)
names(temperature) <- c("long", "lat", "tavg")
temperature_transformed <-
  usmap::usmap_transform(
    temperature,
    input_names = c("long", "lat"),
    output_names = c("x", "y")
  )

# Create a bounding box for limits of this study
bb2 <-
  c(
    "xmin" = -112.81446,
    "xmax" = -105.52416,
    "ymin" = 32.65757,
    "ymax" = 38.089
  ) %>%
  sf::st_bbox() %>%
  sf::st_as_sfc() %>%
  sf::st_as_sf(crs = 4326) %>%
  sf::st_transform(crs = 4326)


ggplot() +
  geom_raster(
    data = temperature_transformed,
    aes(x = long, y = lat, fill = tavg),
    alpha = 0.8,
    na.rm = TRUE
  ) +
  scale_fill_gradientn(colors = colorRampPalette(rev(RColorBrewer::brewer.pal(11, "RdBu")))(255),
                       #limits = c(-8, 8),
                       na.value = "transparent",
                       name = "Temperature °C") +
  coord_equal() +
  theme_classic() +
  scale_x_continuous(breaks = seq(-115, -103, 2.0),
                     limits = c(-115, -103.2)) +
  scale_y_continuous(breaks = seq(31, 39, 2.0),
                     limits = c(31.25, 39)) +
  geom_sf(
    data = usa,
    color = "#2b2b2b",
    fill = "transparent",
    size = 1.0
  ) +
  geom_sf(
    data = fossil.sites,
    shape = 20,
    fill = "blue",
    size = 3.5
  ) +
  geom_sf(
    data = cities,
    shape = 23,
    fill = "blue",
    size = 3.5
  ) +
  geom_sf(
    data = bb,
    size = 1.5,
    fill = NA,
    aes(colour = "darkgrey",
        linetype = "darkgrey"),
    show.legend = "line",
    inherit.aes = FALSE
  ) +
  geom_sf(
    data = bb2,
    size = 1.5,
    fill = NA,
    aes(colour = "darkolivegreen4",
        linetype = "darkolivegreen4"),
    show.legend = "line",
    inherit.aes = FALSE
  ) +
  scale_color_manual(
    values = c("darkgrey" = "darkgrey", "darkolivegreen4" = "darkolivegreen4"),
    labels = c("Bocinsky and Kohler 2014", "This Study"),
    name = "Data Extent"
  ) +
  scale_linetype_manual(
    values = c("darkgrey" = "solid", "darkolivegreen4" = "dashed"),
    labels = c("Bocinsky and Kohler 2014", "This Study"),
    name = "Data Extent"
  ) +
  shadowtext::geom_shadowtext(
    data = cities3,
    aes(x = long, y = lat, label = name),
    nudge_y = 0.265,
    color = "white",
    size = 4
  ) +
  labs(colour = "") +
  annotate(
    "text",
    x = -109.75,
    y = 38.5,
    label = "UTAH",
    size = 6,
    fontface = 2,
    hjust = 1.0
  ) +
  annotate(
    "text",
    x = -108.25,
    y = 38.5,
    label = "COLORADO",
    size = 6,
    fontface = 2,
    hjust = 0
  ) +
  annotate(
    "text",
    x = -109.75,
    y = 32.3,
    label = "ARIZONA",
    size = 6,
    fontface = 2,
    hjust = 1
  ) +
  annotate(
    "text",
    x = -108.25,
    y = 32.3,
    label = "NEW MEXICO",
    size = 6,
    fontface = 2,
    hjust = 0
  ) +
  theme(
    legend.key.width = unit(1.25, 'cm'),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.text.x = element_text(angle = 90),
    axis.title = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 19, family = "Helvetica")
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/Figure2b.png", dpi = 600)


```


```{r fig3, fig.cap= "Temperature for the North Atlantic using Richard Alley’s (2000) Greenland ice core data for 18,000 BC to present with the Younger Dryas and the general period of the northward expansion of maize agriculture from Mesoamerica into the SWUS highlighted.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}
# Greenland ice core data (used in Huckleberry 2015) from Alley 2000.

alley2000 <-
  read.csv(file = "data-raw/gisp2_temp_accum_alley2000.csv", header = TRUE) %>%
  dplyr::mutate(Age = Age * 1000)  %>%
  dplyr::filter(Age <= 20000) %>% 
  dplyr::mutate(Age = BPtoBCAD(Age))

alley2000 %>%
  ggplot(aes(x = Age, y = Temperature)) +
  geom_line(size = 2) +
  scale_x_continuous(breaks = seq(-18000, 2000, 2000),
                     limits = c(-18000, 2000),
                     minor_breaks=seq(-17000, 2000,by=1000),
                     guide = "axis_minor") +
  scale_y_continuous(breaks = seq(-50, -28, 2),
                     minor_breaks=seq(-49, -29,by=1),
                     guide = "axis_minor") +
  theme_classic() +
  xlab("Years BC/AD") +
  ylab("Temperature °C") +
  annotate(
    "rect",
    xmin = -10851 ,
    xmax = -9551,
    ymin = min(alley2000$Temperature) - 0.5,
    ymax = max(alley2000$Temperature),
    alpha = .2
  ) +
  annotate(
    "text",
    x = -10201,
    y = -27.25,
    label = "Younger \n Dryas",
    size = 8
  ) +
  geom_segment(aes(
    x = -6251,
    y = -36.5,
    xend = -6251,
    yend = -33
  ),
  arrow = arrow(length = unit(0.3, "cm"))) +
  annotate(
    "text",
    x = -6251,
    y = -38,
    label = "6250 BC \n Cold Event",
    size = 8
  ) +
  annotate(
    "rect",
    xmin = -2051,
    xmax = -4051,
    ymin = min(alley2000$Temperature) - 0.5,
    ymax = max(alley2000$Temperature),
    alpha = .2
  ) +
  annotate(
    "text",
    x = -3051,
    y = -27.25,
    label = "Northward Expansion \n of Agriculture",
    size = 8
  ) +
    theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    )
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/Figure3.png", dpi = 600)


```


```{r fig4, fig.cap="Low-frequency component of the Moberg et al. (2005) multi-proxy reconstruction for Northern Hemisphere for AD 133–1925. Anomaly is calculated in comparison to the 1961–1990 average.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

# Moberg et al. 2005 low-frequency reconstruction (only).
Moberg <-
  read.delim(
    "./data-raw/nhtemp-moberg2005.txt",
    header = TRUE,
    sep = "\t",
    dec = "."
  ) [, 1:3] %>%
  dplyr::filter(LF > -9.89 & date <= 2000)

ggplot(data = Moberg, aes(x = date, y = LF)) +
  geom_line(size = 2, color = "#A60F2D") +
  xlab("Years AD") +
  ylab("Temperature Anomaly (°C)") +
  scale_x_continuous(breaks=seq(0,2000,200),
                     minor_breaks=seq(100, 1900,by=200),
                     guide = "axis_minor") +
  scale_y_continuous(breaks = seq(-0.7, 0, 0.1), 
                     limits = c(-0.7, 0),
                     minor_breaks=seq(-0.65, -0.05,by=0.05),
                     guide = "axis_minor") +
  theme_bw() +
  geom_hline(yintercept = 0, color = "darkgrey", lty = 2, lwd=1.25) +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/Figure4.png", dpi = 600)

```


```{r fig5, fig.cap="Low-frequency bootstrapped temperature anomaly loess reconstruction from this study (blue) with standard error (gray). Boxplots show estimates binned by century. Anomalies are calculated in comparison to the 1961–1990 average. The temperature predictions for each sample (not binned by century) are shown by circles; sizes of circles are inversely proportional to the sample-specific errors (size of circle ∝ 1/s1; see Simpson, 2007: 21 for calculation of s1). Anomaly estimates with larger circles are more precise.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

Threebest <- readr::read_rds(here::here("vignettes/data/final_paleomat_dataset3.rds")) %>%
  filter(date >= -3000)

Threebest$century <- round(as.numeric(Threebest$date),-2)

weight <- (1 / Threebest$s1)

Threebest %>%
  ggplot(aes(y = anom_bootstrap)) +
  geom_boxplot(
    aes(x = century, group = century),
    lwd = .25,
    outlier.alpha = NA,
    outlier.shape = NA,
    position = position_dodge2(preserve = "total")
  ) +
  geom_point(aes(x = date), size=weight, shape=1) +
  geom_hline(yintercept = 0,
             linetype = 'dashed',
             color = c('darkslategray')) +
  geom_smooth(method = "loess", span = 0.15, aes(x = date), size = 2, colour = "cornflowerblue") +
  scale_x_continuous(limits = c(-3000, 2100),
                     breaks = seq(-3000, 2000, 500),
                     minor_breaks=seq(-2900, 2000,by=100),
                     guide = "axis_minor") +
  scale_y_continuous(limits = c(-8, 8),
                     breaks = seq(-8, 8, 2),
                     minor_breaks=seq(-7, 7,by=1),
                     guide = "axis_minor") +
  theme_bw() +
  xlab("Years BC/AD") +
  ylab("Temperature Anomaly (°C)") +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/Figure5b.png", dpi = 600)

```

```{r fig6 fig.cap="Low-frequency July temperature anomaly for the SWUS from this study, the North American July temperature reconstruction (Viau et al., 2006) from 3000 BC to AD 2000, and the terrestrial composite for 30–60 °N (Kaufman et al., 2020), from 3300 BC to AD 1700, in 500-year bins. All series standardized to a mean of 0 and an s of 1 over the period in this graph.", echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

#scaleFUN <- function(x) sprintf("%.2f", x)

# For our reconstruction, we first extract the fitted values from the loess line, as plotting above.
p <- Threebest %>%
  filter(date >= -3000) %>%
  qplot(date, anom_bootstrap, data = .) +
  stat_smooth(aes(outfit = fit <<- ..y..), span = 0.15, n = 5000)

anom_loess4 <- ggplot_build(p)$data[[2]]

viau <- read.csv("./data-raw/viau.csv") %>% 
  dplyr::mutate(time = BPtoBCAD(time))

kaufman_standard <- read.csv("./data-raw/Kaufman 2020_Figure6Data.csv") %>% 
  dplyr::mutate(time = BPtoBCAD(time_bp),
                Series = "Kaufman et al. 2020") %>% 
  dplyr::select(year = time, anom = zscore, Series) %>% 
  dplyr::filter(year > -3400)

temp_anom_standard <- anom_loess4 %>% 
  dplyr::mutate(x = as.integer(x)) %>% 
  dplyr::filter(x >= -3000 & x <= 1951) %>% 
  dplyr::mutate(Series = "This study") %>% 
  dplyr::select(year = x, anom = y, Series)

viau_standard <- viau %>% 
  dplyr::mutate(Series = "Viau et al. 2006") %>% 
  dplyr::select(year = time, anom = temp, Series) %>% 
  filter(year >= -3000 & year <= 1951)

viau_paleomat_kaufman <- bind_rows(temp_anom_standard, viau_standard, kaufman_standard)

viau_paleomat_kaufman$Series <- factor(viau_paleomat_kaufman$Series, c("Viau et al. 2006", "Kaufman et al. 2020", "This study"))

# Viau and paleomat
viau_paleomat_kaufman %>% 
  mutate(Alpha = case_when(Series == "This study" ~ 1,
                           TRUE ~ 0.65)) %>% 
  group_by(Series) %>% 
  dplyr::mutate(update = (anom - mean(anom)) / sd(anom)) %>% 
  ggplot(aes(x = year, y = update, colour = Series, alpha = Alpha)) +
  geom_hline(yintercept = 0, color = "darkgrey", lty = 2, lwd = 1.25) +
  geom_line(aes(size = Series)) +
  scale_size_manual(values = c(0.75, 0.75, 2)) +
  scale_alpha_identity() +
  scale_color_manual(values=c("darkolivegreen", "#D55E00", "cornflowerblue")) +
  scale_x_continuous(
                     breaks = seq(-3500, 2000, 500), 
                     minor_breaks=seq(-3400,1900,by=100),
                     guide = "axis_minor") +
  scale_y_continuous(breaks = seq(-2, 3.5, 0.5)) +
  xlab("Years BC/AD") +
  ylab("Standardized Temperature Values (Z-Scores)") +
  theme_bw() +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    ),
    legend.text = element_text(size = 19, family = "Helvetica"),
    legend.title = element_blank()
  )


#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/Figure6.png", dpi = 600)


```


```{r fig7, fig.cap="Low-frequency July temperature anomaly for the SWUS from this study and the Northern Hemisphere low-frequency component (Moberg et al. 2005) from AD 133 to 1900. Both series have been standardized to a mean of 0 and an s of 1 for this period.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

temp_anom_standard <- anom_loess4 %>% 
  dplyr::mutate(x = as.integer(x)) %>% 
  dplyr::filter(x >= 133 & x <= 1900) %>% 
  dplyr::mutate(Series = "This study") %>% 
  dplyr::select(year = x, anom = y, Series)

Moberg_standard <- Moberg %>% 
  dplyr::mutate(Series = "Moberg et al. 2005") %>% 
  dplyr::select(year = date, anom = LF, Series) %>% 
  filter(year >= 133 & year <= 1900)

Moberg_paleomat <- bind_rows(temp_anom_standard, Moberg_standard)

# Moberg LF and paleomat
Moberg_paleomat %>% 
  group_by(Series) %>% 
  dplyr::mutate(update = (anom - mean(anom)) / sd(anom)) %>% 
  ggplot(aes(x = year, y = update, colour = Series)) +
  geom_hline(yintercept = 0, color = "darkgrey", lty = 2, lwd = 1.25) +
  geom_line(size = 2.0) +
  scale_color_manual(values=c("#A60F2D", "cornflowerblue")) +
  xlab("Years AD") +
  ylab("Standardized Temperature Values (Z-Scores)") +
  scale_x_continuous(limits = c(100, 1900),
                     breaks = seq(100, 1900, 200), 
                     minor_breaks=seq(200,1800,by=200),
                     guide = "axis_minor") +
  scale_y_continuous(breaks = seq(-2, 3, 0.5)) +
  theme_bw() +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    ),
    legend.text = element_text(size = 19, family = "Helvetica"),
    legend.title = element_blank()
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/Figure7.png", dpi = 600)


```


# Tables

```{r table1, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='asis'}

# Pulling together information for Table 1, except for references, which are done elsewhere.

fossil_metadata_counts_final2 <-
  readr::read_rds(here::here("vignettes/data/fossil_metadata_counts_final2.rds"))

sig_pass <-
  readr::read_rds(here::here("vignettes/data/sig_results2_final.rds")) %>%
  mutate(pass = ifelse(pvalue <= 0.10, "Yes", "No")) %>%
  dplyr::select(dataset.id, pass)

table1 <-
  fossil_metadata_counts_final2 %>%
  filter(age <= 5500) %>%
  dplyr::select(site.name, site.id, dataset.id, elev) %>%
  group_by(site.name, site.id, dataset.id, elev) %>%
  count() %>%
  tidyr::extract(geometry, c('long', 'lat'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  dplyr::select(-geometry) %>%
  dplyr::arrange(site.name) %>%
  dplyr::left_join(., sig_pass, by = "dataset.id") %>%
  dplyr::mutate(pass = ifelse(is.na(pass), "NA (removed in a previous step)", pass)) %>%
  dplyr::select(
    "Site Name" = site.name,
    "Site ID" = site.id,
    "Dataset ID" = dataset.id,
    "No. of Samples" = n,
    "Elevation (m)" = elev,
    "Longitude" = long,
    "Latitude" = lat,
    "Pass significance test?" = pass
  )

knitr::kable(table1,
             caption = "Metadata for the fossil pollen records (37 sites or 41 datasets) used in this study that have data after 3,550 BC. All data were downloaded from the Neotoma Paleoecological Database (Williams et al., 2018).")

```

# Supplemental Materials

## Supplemental Tables

```{r supptable1, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='asis'}

fossil_final_west_metadata_post5500BP <-
  readr::read_rds(here::here("vignettes/data/fossil_final_west_metadata_post5500BP.rds")) %>%
  ungroup %>%
  dplyr::select(site.name, site.id, dataset.id) %>% 
  filter(dataset.id %in% c(250L, 347L, 498L, 517L, 1013L, 1162L, 1660L, 1717L, 1761L, 
      1762L, 1766L, 1970L, 2320L, 2880L, 2897L, 2950L, 3054L, 3056L, 
      3060L, 3560L, 3561L, 3608L, 3612L, 14517L, 14547L, 14549L, 14650L, 
      14944L, 14951L, 15106L, 15356L, 15967L, 17419L, 20304L, 20833L, 
      20838L, 22948L, 25551L, 41580L, 42645L, 46801L)) %>% 
  distinct() %>%
  st_drop_geometry()

Threebest <-
  readr::read_rds(here::here("vignettes/data/final_paleomat_dataset3.rds")) %>%
  filter(date >= -3000)

summary_table <- Threebest %>%
  group_by(dataset.id) %>%
  summarise(
    anom_range = max(anom) - min(anom),
    anom_bootstrap_range = max(anom_bootstrap) - min(anom_bootstrap),
    rmsep_mean = mean(rmsep),
    s1_mean = mean(s1)
  )

summary_table_final <-
  readr::read_rds(here::here("vignettes/data/sig_results2_final.rds")) %>%
  left_join(.,
            fossil_final_west_metadata_post5500BP,
            by = "dataset.id") %>%
  dplyr::select(site.name, site.id, dataset.id, proportion, pvalue) %>%
  left_join(., summary_table, by = "dataset.id") %>%
  mutate(a = ifelse(!is.na(anom_range), 1, 2)) %>%
  arrange(a, site.name) %>%
  dplyr::select(-a) %>%
  filter(!is.na(site.name)) %>%
  mutate(across(c(proportion, pvalue), ~ as.numeric(.x))) %>%
  mutate(across(-c(site.name, site.id, dataset.id), ~ round(.x, digits =
                                                              2)))

names(summary_table_final) <-
  c(
    "Site Name",
    "Site ID",
    "Dataset ID",
    "Proportion explained variance",
    "Random TF p",
    "Anomaly (°C)",
    "Anomaly Bootstrapped (°C)",
    "Mean boostrap RMSEP (°C)",
    "Mean boostrap s1"
  )

if (!file.exists(here::here("./vignettes/data/summary_table_final.csv"))) {
  write.csv(summary_table_final,
            "./vignettes/data/summary_table_final.csv",
            row.names = FALSE)
}

knitr::kable(summary_table_final,
             caption = "Metadata for the fossil pollen records used in this study.")


```


# Supplemental Figures

```{r suppfig1, fig.cap="Squared residual length for the fossil assemblages vs age. Red line marks the 95% limit of the calibration set residual lengths (very poorly fitted). We removed all samples that fell above the 95% line.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

ff <- readr::read_rds(here::here("./vignettes/data/fossil_final_west_metadata_post5500BP.rds")) %>% 
  filter(!is.na(age) & age <= 5500) %>% 
  dplyr::select(sample.id, age) %>% 
  mutate(age = BPtoBCAD(age)) %>% 
  sf::st_drop_geometry()


rlen_results_filtered <- readr::read_rds(here::here("./vignettes/data/rlen_full_results2.rds"))$res_lengths %>% 
  left_join(., ff, by = "sample.id")

ninety5quant <- readr::read_rds(here::here("./vignettes/data/rlen_full_results2.rds"))$quantile_95

ggplot(data = rlen_results_filtered, aes(x = age, y = Squared_res_lengths)) +
  geom_point() +
  xlab("Years BC/AD") +
  ylab("Squared Residual Length") +
  scale_x_continuous(limits = c(-3500, 2100),
                     breaks = seq(-3500, 2000, 500),
                     minor_breaks=seq(-3400, 1900,by = 100),
                     guide = "axis_minor") +
  scale_y_continuous(limits = c(0, 260),
                     breaks = seq(0, 260, 20),
                     minor_breaks=seq(10, 240, 10),
                     guide = "axis_minor") +
  theme_bw() +
  geom_hline(yintercept = ninety5quant, color = "red", lty = 1, lwd=0.5) +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/SuppFigure1.png", dpi = 600)


```


```{r suppfig2, fig.cap="Summary diagram of the results of a MAT model applied to predict temperature from the modern pollen data set. The leave-one-out error measure (RMSEP) shows that 4 analogs provide the optimal choice (lowest RMSEP).", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

mat_calibration <- readr::read_rds(here::here("./vignettes/data/mat_calibration.rds"))

tbl <- cbind(mat_calibration$standard$rmsep[1:20], mat_calibration$standard$r.squared[1:20],
             mat_calibration$standard$avg.bias[1:20], mat_calibration$standard$max.bias[1:20])

tbl <- as.matrix(format(tbl, digits = 3))

tbl <- cbind(as.integer(1:20), tbl)

rownames(tbl) <- rep("", nrow(tbl))
colnames(tbl) <- c("k", "RMSEP","R2","Avg Bias","Max Bias")

as.data.frame(tbl) %>% 
  mutate(across(everything(), ~ as.numeric(.x))) %>% 
  ggplot(aes(x = k, y = RMSEP)) +
  geom_line(size = 1) +
  geom_label(aes(label = k), fill = "white", label.size = NA, size = 5.5) +
  xlab("Number of Analogues (k)") +
  ylab("RMSEP") +
  scale_x_continuous(breaks=seq(0,20,2),
                     minor_breaks=seq(1, 19,by=1),
                     guide = "axis_minor") +
  scale_y_continuous(breaks = seq(2.10, 2.45, 0.05), 
                     limits = c(2.10, 2.45),
                     minor_breaks=seq(2.11, 2.44,by=0.01),
                     guide = "axis_minor") +
  theme_bw() +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/SuppFigure2.png", dpi = 600)

```

```{r suppfig3, fig.cap="Time series plot of the minimum dissimilarity between each core (fossil) sample and the modern pollen training set samples. The dotted, horizontal lines are drawn at various percentiles of the distribution of the pair-wise dissimilarities for the training set samples. We used the 5th percentile as the cutoff for good analogs. So, samples with distances greater than the 5th percentile (above the line) were removed.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

minDC_df <- readr::read_rds(here::here("./vignettes/data/minDC_full_results.rds"))$minDC %>% 
  arrange(age)

# Keeping only 1%, 2.5%, and 5%, as I don't want to plot 10%.
minDC_quantiles <- readr::read_rds(here::here("./vignettes/data/minDC_full_results.rds"))$quantiles[1:3]

ggplot(data = minDC_df, aes(x = age, y = values)) +
  xlab("Years BC/AD") +
  ylab("Dissimilarity") +
  scale_x_continuous(limits = c(-3500, 2100),
                     breaks = seq(-3500, 2000, 500),
                     minor_breaks=seq(-3400, 1900,by = 100),
                     guide = "axis_minor") +
  scale_y_continuous(limits = c(0, 0.35),
                     breaks = seq(0, 0.35, 0.05)) +
  theme_bw() +
  annotate("label", x = Inf, y = c(0.1139258, 0.1650981, 0.2171289), label = c("1%", "2.5%", "5%"), hjust = 0, size = 8, fill = "white", label.size = NA) +
  coord_cartesian(xlim = c(-3500, 2000), clip = "off") +
  geom_hline(yintercept = minDC_quantiles, color = "red", lty = "dashed", lwd=0.5) +
  geom_point() +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 75,
      b = 5,
      l = 5
    )
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/SuppFigure3.png", dpi = 600)


```


```{r suppfig4, fig.cap="Linear regression and scatterplot between temperature anomaly predicted values and the bootstrapped temperature predictions. There is a strong linear relationship across their joint ranges (r2 = 0.96; p > F < .001).", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

Threebest <- readr::read_rds(here::here("vignettes/data/final_paleomat_dataset3.rds")) %>%
  filter(date >= -3000)

Threebest %>%
  ggplot(aes(x = anom, y = anom_bootstrap)) +
    geom_point() +
  stat_smooth(method = "lm", col = "red") +
  scale_x_continuous(limits = c(-9, 9),
                     breaks = seq(-9, 9, 2),
                     minor_breaks=seq(-8, 8,by=1),
                     guide = "axis_minor") +
  scale_y_continuous(limits = c(-9, 9),
                     breaks = seq(-9, 9, 2),
                     minor_breaks=seq(-8, 8,by=1),
                     guide = "axis_minor") +  
  theme_bw() +
  xlab("Temperature Anomaly Predicted Values") +
  ylab("Bootstrapped Temperature Predictions") +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/SuppFigure4.png", dpi = 600)


```



```{r suppfig5, fig.cap="Low-frequency weighted bootstrapped temperature anomaly loess reconstruction from this study (blue) with standard error (gray). As in Figure 5 (main text) except here the loess curve (only) is weighted by the inverse of the sample-specific errors s1; see Simpson, 2007: 21 for calculation). Bubble size α 1/s1.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'}

Threebest <- readr::read_rds(here::here("vignettes/data/final_paleomat_dataset3.rds")) %>%
  filter(date >= -3000)

Threebest$century <- round(as.numeric(Threebest$date),-2)

weight <- (1 / Threebest$s1)

Threebest %>%
  ggplot(aes(y = anom_bootstrap)) +
  geom_point(aes(x = date), size=weight, shape=1) +
  geom_boxplot(
    aes(x = century, group = century),
    lwd = .25,
    outlier.alpha = NA,
    outlier.shape = NA,
    position = position_dodge2(preserve = "total")
  ) +
  geom_hline(yintercept = 0,
             linetype = 'dashed',
             color = c('darkslategray')) +
  geom_smooth(method = "loess", span = 0.15, aes(x = date, weight = weight), size = 2, colour = "cornflowerblue") +
  scale_x_continuous(limits = c(-3000, 2100),
                     breaks = seq(-3000, 2000, 500),
                     minor_breaks=seq(-2900, 2000,by=100),
                     guide = "axis_minor") +
  scale_y_continuous(limits = c(-8, 8),
                     breaks = seq(-8, 8, 2),
                     minor_breaks=seq(-7, 7,by=1),
                     guide = "axis_minor") +
  theme_bw() +
  xlab("Years BC/AD") +
  ylab("Temperature Anomaly (°C)") +
  theme(
    axis.ticks.length=unit(0.125,"inch"),
    ggh4x.axis.ticks.length.minor = rel(0.5),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 26,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 5,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 5,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.margin = margin(
      t = 5,
      r = 25,
      b = 5,
      l = 5
    )
  )

#ggsave("~/Dropbox/WSU/SKOPEII/model/Final_Figures/SuppFigure5.png", dpi = 600)


```


<!-- ```{r old_matanom} -->
<!-- # Temperature anomaly across time for the spatial extent in each 100 year interval. -->
<!-- temp_anom <- read.csv("./output/paleomat-temp-anomaly-final.csv") -->

<!-- #samples <- data.frame(x = c(0, 100, 500, 1000), y = c(-3.5, -3.5, -3.5, -3.5)) -->
<!-- samples <- tavg_new_90 %>% -->
<!--   ungroup %>% -->
<!--   dplyr::select(date) %>% -->
<!--   mutate(y = -3.0) %>% -->
<!--   rename(x = date) -->


<!-- site.preds.unlisted.anom %>%  -->
<!--   #filter(site.id == 246) %>%  -->
<!--   #filter(site.id != 1710) %>%  -->
<!--   group_by(date) %>%  -->
<!--   #mutate(anom = anom - mean(site.preds.unlisted.anom$anom)) %>%  -->
<!--   #mutate(anom = anom/10) -->
<!--   #dplyr::summarise(temp = mean(anom), twenty_five = quantile(anom, 0.25), seventy_five = quantile(anom, 0.75), IQR = IQR(anom)) %>%  -->
<!--   dplyr::summarise(temp = mean(anom), se = sd(anom)/sqrt(n())) %>%  -->
<!--   #mutate(anom = temp - warmest.month) %>%  -->
<!--   #bp_95 %>%  -->
<!--   ggplot(aes(x = date, y = temp)) + -->
<!--   #geom_ribbon(aes(ymin = twenty_five, ymax = seventy_five), fill = "grey90") + -->
<!--   geom_ribbon(aes(ymin = temp-se, ymax = temp+se), fill = "grey90") + -->
<!--   geom_line(colour = "red", size = 1.0) + -->
<!--   #theme_bw() -->
<!--   #geom_line(aes(y=rollmean(temp, 3, na.pad=TRUE))) + -->
<!--   #geom_smooth(method="auto", se=TRUE, fullrange=FALSE, level=0.95) + -->
<!--   #geom_point() + -->
<!--   xlab("Year BC/AD") + -->
<!--   ylab("July Temperature Anomaly (°C)") + -->
<!--   # scale_x_continuous(breaks = seq(-1000, 1800, 200), -->
<!--   #                    minor_breaks = seq((-1000 + 100), (1800 - 100), 200)) + -->
<!--   # scale_y_continuous(breaks = seq(10, 18, 1), -->
<!--   #                   limits = c(10, 18)) + -->
<!--   theme_bw() + -->
<!--   scale_x_continuous(breaks = seq(-3000, 2000, 500), -->
<!--                      #minor_breaks = seq(-3100, 1900, 200), -->
<!--                      minor_breaks = NULL, -->
<!--                      limits = c(-3000, 2000)) + -->
<!--   scale_y_continuous(breaks = seq(-2.0, 2.0, 1.0), -->
<!--                      limits = c(-2.0, 2.5), -->
<!--                      expand = c(0.01, 0)) + -->
<!--   #geom_vline(xintercept = c(883, 1150, 1290, 1590)) + -->
<!--   #geom_vline(xintercept = c(800, 1200, 1400, 1800)) + -->
<!--   #geom_vline(xintercept = c(570, 1280)) + -->
<!--   geom_hline(yintercept = 0, colour = "grey40", linetype = "dashed", size=1.5) + -->
<!--   #geom_point(data = samples, shape = "|", size = 3,  aes(x = x, y = y)) + -->
<!--   geom_rug(data = samples, aes(x = x, y = NULL), sides="b") + -->
<!--   # annotate( -->
<!--   #   "rect", -->
<!--   #   xmin = 800, -->
<!--   #   xmax = 1200, -->
<!--   #   ymin = -2.0, -->
<!--   #   ymax = 0.0, -->
<!--   #   alpha = .2 -->
<!--   # ) + -->
<!--   # annotate( -->
<!--   #   "text", -->
<!--   #   x = 1000, -->
<!--   #   y = 0.5, -->
<!--   #   label = "Medieval \n Warm \n Period", -->
<!--   #   size = 5.25 -->
<!--   # ) + -->
<!--   #   annotate( -->
<!--   #   "rect", -->
<!--   #   xmin = 1400, -->
<!--   #   xmax = 1800, -->
<!--   #   ymin = -2.0, -->
<!--   #   ymax = 0.0, -->
<!--   #   alpha = .2 -->
<!--   # ) + -->
<!--   # annotate( -->
<!--   #   "text", -->
<!--   #   x = 1600, -->
<!--   #   y = 0.5, -->
<!--   #   label = "Little \n Ice \n Age", -->
<!--   #   size = 5.25 -->
<!--   # ) + -->
<!-- #ggtitle("Low-frequency Temperature Reconstruction using the Modern Analogue Technique") + -->
<!--   theme( -->
<!--     panel.border = element_blank(), -->
<!--     #panel.grid.major = element_blank(), -->
<!--     panel.grid.minor.y = element_blank(), -->
<!--     #panel.grid.major.y = element_blank(), -->
<!--     axis.text = element_text( -->
<!--       size = 22, -->
<!--       colour = "black", -->
<!--       family = "Helvetica" -->
<!--     ), -->
<!--     axis.title.y = element_text( -->
<!--       size = 23, -->
<!--       family = "Helvetica", -->
<!--       margin = margin( -->
<!--         t = 10, -->
<!--         r = 6, -->
<!--         b = 10, -->
<!--         l = 10 -->
<!--       ) -->
<!--     ), -->
<!--     axis.title.x = element_text( -->
<!--       size = 23, -->
<!--       family = "Helvetica", -->
<!--       margin = margin( -->
<!--         t = 6, -->
<!--         r = 10, -->
<!--         b = 10, -->
<!--         l = 10 -->
<!--       ) -->
<!--     ), -->
<!--     #panel.grid.minor = element_line(colour = "light grey"), -->
<!--     axis.line = element_line(colour = "black"), -->
<!--     plot.title = element_text(size = 21, face = "bold", family = "Helvetica") -->
<!--   ) -->

<!-- #ggsave("Anom_JustNoAnalgoue.png", width = 14.3, height = 7.5, units = "in", dpi = 600) -->


<!-- ``` -->



<!-- ```{r old_fig6, fig.cap="The spatial interpolation of the low-frequency temperature reconstruction for this study. The extent can be seen by the red box in Figure 3.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'} -->

<!-- tavg_rasters <- stack("./output/paleomat-rasters.tif") -->

<!-- # library(ggnewscale) -->
<!-- #  -->
<!-- # # setting up bounding box -->
<!-- # locations <- data.frame(x = c(-112.81446, -105.52416), -->
<!-- #                         y = c(32.65757, 38.089)) -->

<!-- # -112.81446, -->
<!-- #     "xmax" = -105.52416, -->
<!-- #     "ymin" = 32.65757, -->
<!-- #     "ymax" = 38.089 -->

<!-- # # get gem -->
<!-- # dem <- get_elev_raster(locations = bb2, prj = sf::st_crs(4326), z = 7, clip = "bbox") -->
<!-- # temp.raster <- raster::crop(temp.raster, bb2) -->
<!-- # temp.raster <- -->
<!-- #   raster::projectRaster(temp.raster, crs = CRS("+init=epsg:4326")) -->
<!-- #  -->
<!-- # # create slope and hillshade -->
<!-- # slope = terrain(dem, opt='slope') -->
<!-- # aspect = terrain(dem, opt='aspect') -->
<!-- # hill = hillShade(slope, aspect, 40, 270) -->
<!-- # hill_spdf <- as(hill, "SpatialPixelsDataFrame") -->
<!-- # hill_spdf <- as.data.frame(hill_spdf) -->
<!-- # colnames(hill_spdf) <- c("value", "x", "y") -->


<!-- rasterVis::gplot(tavg_idw_stack, layout=c(5, 3)) + -->
<!--   # geom_tile(data = hill_spdf, aes(x = x, y = y, fill = value)) + -->
<!--   geom_tile(aes(fill = value)) + -->
<!--   facet_wrap(~ variable) + -->
<!--   scale_fill_gradientn(colours = colorRampPalette(rev(RColorBrewer::brewer.pal(11, "RdBu")))(255)) + -->
<!--   coord_equal() + -->
<!--   theme_bw() + -->
<!--   xlab("Longitude") + -->
<!--   ylab("Latitude") + -->
<!--   labs(fill='Anomaly') -->

<!-- trellis.device(pdf, file='idw_interpolation.pdf', height=11.7, width=8.3) -->
<!-- rasterVis::levelplot(tavg_idw_stack, -->
<!--           layout=c(4, 7), # create a 5x3 layout for the data -->
<!--           col.regions=colorRampPalette(rev(RColorBrewer::brewer.pal(11, "RdBu")))(255)) -->

<!-- dev.off() -->

<!-- # names(tavg_idw) <- c("BC950","BC850","BC750", "BC650", "BC550","BC450", "BC350", "BC250", "BC150", "BC50", "AD50", "AD150", "AD250", "AD350", "AD450", "AD550", "AD650", "AD750", "AD850","AD950", "AD1050", "AD1150", "AD1250", "AD1350", "AD1450", "AD1550", "AD1650", "AD1750") -->
<!-- # -->
<!-- # anomaly_plots <- -->
<!-- #   purrr::map2( -->
<!-- #     .x = tavg_idw, .y = names(tavg_idw), -->
<!-- #     .f = -->
<!-- #       ~plot_map_anomaly(x = .x, x.name = .y, us.cities = us.cities, cities = FALSE, animation = FALSE) -->
<!-- #   ) -->


<!-- # temp.raster <- -->
<!-- #   raster::projectRaster(tavg_nrg[[23]], crs = CRS("+init=epsg:4326")) -->
<!-- #  -->
<!-- #  -->
<!-- # usa <- sf::st_as_sf(maps::map("state", fill = TRUE, plot = FALSE)) -->
<!-- # usa <- sf::st_transform(usa, crs = 4326) -->
<!-- #  -->
<!-- # crs(temp.raster) <- -->
<!-- #   "+proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +ellps=GRS80 +datum=WGS84 +units=m +no_defs" -->
<!-- # temperature <- as.data.frame(temp.raster, xy = TRUE) -->
<!-- # temperature_transformed <- usmap::usmap_transform(temperature) -->
<!-- #  -->
<!-- #  -->
<!-- # ggplot() + -->
<!-- #   geom_raster( -->
<!-- #     data = temperature_transformed, -->
<!-- #     aes(x = x, y = y, fill = paleomat.rasters.23), -->
<!-- #     alpha = 0.8, -->
<!-- #     na.rm = TRUE -->
<!-- #   ) + -->
<!-- #   scale_fill_gradientn(colors = colorRampPalette(rev(RColorBrewer::brewer.pal(11, "RdBu")))(255), -->
<!-- #                        #limits = c(-8, 8), -->
<!-- #                        na.value = "transparent", -->
<!-- #                        name = "Temperature °C") + -->
<!-- #   coord_equal() + -->
<!-- #   theme_classic() -->


<!-- ``` -->



<!-- ```{r fig7, fig.cap="July temperature anomaly for two Village Ecodynamics Project (VEP) areas, VEPIIS and VEPIIN (Schwindt et al. 2016).", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'} -->

<!-- vepii_cmv_boundary <- st_transform(vepii_cmv_boundary, crs = st_crs(4326)) %>%  -->
<!--   sf::st_as_sf(crs = 4326) %>% -->
<!--   sf::st_transform(crs = 4326) -->

<!-- tavg_cmv <- brick("./output/paleomat-rasters.tif") %>% -->
<!--   unstack() %>%  -->
<!--   purrr::map(., raster::crop, vepii_cmv_boundary) -->

<!-- vepii_nrg_boundary <- st_transform(vepii_nrg_boundary, crs = st_crs(4326)) %>%  -->
<!--   sf::st_as_sf(crs = 4326) %>% -->
<!--   sf::st_transform(crs = 4326) -->

<!-- tavg_nrg <- brick("./output/paleomat-rasters.tif") %>% -->
<!--   unstack() %>%  -->
<!--   purrr::map(., raster::crop, vepii_nrg_boundary) -->

<!-- # Calculate the anomaly across time for CMV (or VEPIIN) (to produce line graph). -->
<!-- anom_cmv <- purrr::map(tavg_cmv, cellStats, mean) %>%  -->
<!--   as.data.frame() %>%  -->
<!--   tidyr::pivot_longer(cols = 1:28) %>%  -->
<!--   dplyr::mutate(name = seq(-950, 1750, 100)) %>%  -->
<!--   dplyr::rename(year = name, anom = value) %>%  -->
<!--   dplyr::mutate(Series = "VEPIIN") -->

<!-- # anom_cmv <- anom_cmv %>% -->
<!-- #   dplyr::mutate(updated = (anom - mean(anom_cmv$anom)) / sd(anom_cmv$anom)) %>%  -->
<!-- #   dplyr::mutate(series = "CMV") -->

<!-- # Calculate the anomaly across time for NRP (or VEPIIS) (to produce line graph). -->
<!-- anom_nrg <- purrr::map(tavg_nrg, cellStats, mean) %>%  -->
<!--   as.data.frame() %>%  -->
<!--   tidyr::pivot_longer(cols = 1:28) %>%  -->
<!--   dplyr::mutate(name = seq(-950, 1750, 100)) %>%  -->
<!--   dplyr::rename(year = name, anom = value) %>%  -->
<!--   dplyr::mutate(Series = "VEPIIS") -->

<!-- # anom_nrg <- anom_nrg %>% -->
<!-- #   dplyr::mutate(updated = (anom - mean(anom_nrg$anom)) / sd(anom_nrg$anom)) %>%  -->
<!-- #   dplyr::mutate(series = "NRG") -->

<!-- VEPII <- rbind(anom_cmv, anom_nrg) -->


<!-- # Plot both together -->
<!-- VEPII %>% -->
<!--   #dplyr::filter(year > 0) %>%  -->
<!--   ggplot(aes(x = year, y = anom, colour=Series)) + -->
<!--   geom_line(size = 1.0) + -->
<!--   xlab("Year BC/AD") + -->
<!--   ylab("July Temperature Anomaly (°C)") + -->
<!--   scale_x_continuous(breaks = seq(-1000, 1800, 200), -->
<!--                      minor_breaks = seq((-1000 + 100), (1800 - 100), 200)) + -->
<!--   scale_y_continuous(breaks = seq(-2.5, 1.0, 0.5), -->
<!--                      limits = c(-2.5, 1.0)) + -->
<!--   theme_bw() + -->
<!--   # annotate( -->
<!--   #   "rect", -->
<!--   #   xmin = 800, -->
<!--   #   xmax = 1200, -->
<!--   #   ymin = -2.5, -->
<!--   #   ymax = 0.0, -->
<!--   #   alpha = .2 -->
<!--   # ) + -->
<!--   # annotate( -->
<!--   #   "text", -->
<!--   #   x = 1000, -->
<!--   #   y = -0.25, -->
<!--   #   label = "Medieval Warm \n Period", -->
<!--   #   size = 4.5 -->
<!--   # ) + -->
<!--   #   annotate( -->
<!--   #   "rect", -->
<!--   #   xmin = 1400, -->
<!--   #   xmax = 1800, -->
<!--   #   ymin = -2.5, -->
<!--   #   ymax = 0.0, -->
<!--   #   alpha = .2 -->
<!--   # ) + -->
<!--   # annotate( -->
<!--   #   "text", -->
<!--   #   x = 1600, -->
<!--   #   y = -0.25, -->
<!--   #   label = "Little Ice \n Age", -->
<!--   #   size = 4.5 -->
<!--   # ) + -->
<!--   theme( -->
<!--     panel.border = element_blank(), -->
<!--     panel.grid.major = element_blank(), -->
<!--     axis.text = element_text( -->
<!--       size = 12, -->
<!--       colour = "black", -->
<!--       family = "Helvetica" -->
<!--     ), -->
<!--     axis.title.y = element_text( -->
<!--       size = 14, -->
<!--       family = "Helvetica", -->
<!--       margin = margin( -->
<!--         t = 10, -->
<!--         r = 6, -->
<!--         b = 10, -->
<!--         l = 10 -->
<!--       ) -->
<!--     ), -->
<!--     axis.title.x = element_text( -->
<!--       size = 14, -->
<!--       family = "Helvetica", -->
<!--       margin = margin( -->
<!--         t = 6, -->
<!--         r = 10, -->
<!--         b = 10, -->
<!--         l = 10 -->
<!--       ) -->
<!--     ), -->
<!--     panel.grid.minor = element_line(colour = "light grey"), -->
<!--     axis.line = element_line(colour = "black") -->
<!--   ) -->


<!-- ``` -->

<!-- ```{r fig8, fig.cap="Comparison of low-frequency reconstruction from this study, crop productivity, and niche.", fig.width=10.5, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'} -->

<!-- years <- 1:1300 -->

<!-- paleomat <- site.preds.unlisted.anom %>%  -->
<!--   dplyr::filter(date >= 1 & date <= 1250) %>%  -->
<!--   group_by(date) %>%  -->
<!--   dplyr::summarise(temp = mean(anom)) %>%  -->
<!--   dplyr::mutate(updated = (temp - mean(temp)) / sd(temp)) %>%  -->
<!--   select(-temp) -->
<!--   #dplyr::mutate(updated = (anom - mean(paleomat$anom)) / sd(paleomat$anom)) -->

<!-- # paleomat <- -->
<!-- #   read.csv(file = "./output/paleomat-temp-anomaly-final.csv", header = TRUE) %>% -->
<!-- #   dplyr::filter(year >= 1 & year <= 1250) -->
<!-- #  -->
<!-- # paleomat <- paleomat %>%  -->
<!-- #   dplyr::mutate(updated = (anom - mean(paleomat$anom)) / sd(paleomat$anom)) -->

<!-- # Estimated potential average maize yield (kg) in the CMV region -->
<!-- years_vep <- data.frame(Year = seq(1, 599, 1)) -->
<!-- vep_paleoprod_mean <- -->
<!--   read.csv("./data-raw/vepiin_paleoprod_stats.csv") -->
<!-- vep_paleoprod_mean <- -->
<!--   dplyr::bind_rows(years_vep, vep_paleoprod_mean) -->

<!-- vep_paleoprod_mean <- vep_paleoprod_mean %>%  -->
<!--   dplyr::mutate(updated = (`Average.prod..linear.lagged.` - mean(vep_paleoprod_mean$`Average.prod..linear.lagged.`, na.rm = TRUE)) / sd(vep_paleoprod_mean$`Average.prod..linear.lagged.`, na.rm = TRUE)) -->


<!-- # Proportion of the CMV region in the maize dry-farming niche -->
<!-- vep_niche_percent <- read.csv("./data-raw/vepiin_niche_stats.csv") -->

<!-- vep_niche_percent <- vep_niche_percent %>%  -->
<!--   dplyr::mutate(updated = (`Prop.in.niche..linear.lagged.` - mean(vep_niche_percent$`Prop.in.niche..linear.lagged.`, na.rm = TRUE)) / sd(vep_niche_percent$`Prop.in.niche..linear.lagged.`, na.rm = TRUE)) -->


<!-- all_reconstructions <- vep_paleoprod_mean %>% -->
<!--   dplyr::select(Year, `Average.prod..linear.lagged.`) %>% -->
<!--   dplyr::rename( -->
<!--     "Average Crop Productivity (Unweighted Average of the Current Year and the Previous 20 [i.e., linear lagged])" = 2 -->
<!--   ) %>% -->
<!--   dplyr::left_join( -->
<!--     vep_niche_percent %>% dplyr::select(Year, `Prop.in.niche..linear.lagged.`) %>% dplyr::rename( -->
<!--       "Proportion in Maize Niche (Unweighted Average of the Current Year and the Previous 20 [i.e., linear lagged])" = 2 -->
<!--     ), -->
<!--     by = "Year" -->
<!--   ) %>% -->
<!--   dplyr::left_join( -->
<!--     paleomat %>% dplyr::rename( -->
<!--       "Year" = 1, -->
<!--       "MAT - Temperature Anomaly °C (100-year Intervals)" = 2 -->
<!--     ) , -->
<!--     by = "Year" -->
<!--   ) %>% -->
<!--   tidyr::pivot_longer(!Year, "Measure", "value") %>% -->
<!--   dplyr::filter(!is.na(value)) -->

<!-- all_reconstructions$Measure_f = factor( -->
<!--   all_reconstructions$Measure , -->
<!--   levels = c( -->
<!--     'Average Crop Productivity (Unweighted Average of the Current Year and the Previous 20 [i.e., linear lagged])', -->
<!--     'Proportion in Maize Niche (Unweighted Average of the Current Year and the Previous 20 [i.e., linear lagged])', -->
<!--     'MAT - Temperature Anomaly °C (100-year Intervals)' -->
<!--   ) -->
<!-- ) -->


<!-- ggplot(all_reconstructions, aes(x = Year)) + -->
<!--   geom_line(aes(y = value)) + -->
<!--   scale_x_continuous( -->
<!--     breaks = c(1, seq(100, 1300, 100)), -->
<!--     limits = c(1, 1300), -->
<!--     expand = c(0, 0) -->
<!--   ) + -->
<!--   ggplot2::xlab("Year AD") + -->
<!--   ggplot2::ylab("") + -->
<!--   ggplot2::theme_linedraw() + -->
<!--   facet_wrap("Measure_f", -->
<!--              ncol = 1, -->
<!--              scales = "free_y") + -->
<!--   guides(fill = "none", color = "none") + -->
<!--   theme(text = element_text(size = 15), -->
<!--         plot.margin = margin(10, 15, 10, 10)) -->

<!-- ggsave("Paleomat_Productivity_Niche.png", width = 14.3, height = 7.5, units = "in", dpi = 600) -->




<!-- # plot together using the standardized values. -->
<!-- # all_reconstructions <- vep_paleoprod_mean %>% -->
<!-- #   dplyr::select(Year, updated) %>% -->
<!-- #   dplyr::rename( -->
<!-- #     "Average Crop Productivity (Unweighted Average of the Current Year and the Previous 20 [i.e., linear lagged])" = 2 -->
<!-- #   ) %>% -->
<!-- #   dplyr::left_join( -->
<!-- #     vep_niche_percent %>% dplyr::select(Year, updated) %>% dplyr::rename( -->
<!-- #       "Proportion in Maize Niche (Unweighted Average of the Current Year and the Previous 20 [i.e., linear lagged])" = 2 -->
<!-- #     ), -->
<!-- #     by = "Year" -->
<!-- #   ) %>% -->
<!-- #   dplyr::left_join( -->
<!-- #     paleomat %>% dplyr::select(year, updated) %>%  -->
<!-- #       dplyr::rename( -->
<!-- #       "Year" = 1, -->
<!-- #       "MAT - Temperature Anomaly °C (100-year Intervals)" = 2 -->
<!-- #     ) , -->
<!-- #     by = "Year" -->
<!-- #   ) %>% -->
<!-- #   tidyr::pivot_longer(!Year, "Measure", "value") %>% -->
<!-- #   dplyr::filter(!is.na(value)) -->
<!-- #  -->
<!-- # all_reconstructions$Measure_f = factor( -->
<!-- #   all_reconstructions$Measure , -->
<!-- #   levels = c( -->
<!-- #     'Average Crop Productivity (Unweighted Average of the Current Year and the Previous 20 [i.e., linear lagged])', -->
<!-- #     'Proportion in Maize Niche (Unweighted Average of the Current Year and the Previous 20 [i.e., linear lagged])', -->
<!-- #     'MAT - Temperature Anomaly °C (100-year Intervals)' -->
<!-- #   ) -->
<!-- # ) -->
<!-- #  -->
<!-- # ggplot(all_reconstructions, aes(x = Year, y = value, colour = Measure)) + -->
<!-- #   geom_line() + -->
<!-- #   scale_x_continuous( -->
<!-- #     breaks = c(1, seq(100, 1300, 100)), -->
<!-- #     limits = c(1, 1300), -->
<!-- #     expand = c(0, 0) -->
<!-- #   ) + -->
<!-- #   ggplot2::xlab("Year AD") + -->
<!-- #   ggplot2::ylab("") + -->
<!-- #   theme(legend.position = "none") + -->
<!-- #   theme(text = element_text(size = 15), -->
<!-- #         plot.margin = margin(10, 15, 10, 10)) -->


<!-- ``` -->



<!-- # Supplementary Figures -->

<!-- ```{r supp_fig1, fig.cap="Temporal interpolation of temperature reconstruction for each fossil pollen site.", echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'} -->

<!-- temporal_interpolations <- readRDS("./output/temporal_interpolations.rds") -->

<!-- # Plot results in one PDF. -->
<!-- # plot_objects <- temporal_interpolations$plot_fit -->
<!-- # names(plot_objects) <- c(temporal_interpolations$site.name) -->

<!-- # Plot the temporal interpolation results in one PDF. -->
<!-- plot_objects <- tavg_predicted_west_new_90$plot_fit -->
<!-- names(plot_objects) <- c(tavg_predicted_west_new_90$site.name) -->

<!-- ok <- ggpubr::ggarrange(plotlist= plot_objects, -->
<!--                     labels = c(names(plot_objects)), -->
<!--                     ncol = 3, nrow = 5, vjust = -0.5) + -->
<!--   theme(plot.margin = margin(1.0,0.1,2,0.1, "cm"))  -->

<!-- ggsave("site_temporal_interpolation.png", ok, width = 16.0, height = 16.0, units = "in") -->

<!-- annotate_figure(ok, top = text_grob("",  -->
<!--                color = "red", face = "bold", size = 14)) -->

<!-- # plot_objects_arranged <- gridExtra::marrangeGrob(plot_objects, nrow=7, ncol=5, top=quote(names(plot_objects)[g])) -->
<!-- # ggsave("./output/temporal_interpolations_plots.pdf", plot_objects_arranged, scale = 1.5) -->


<!-- # Plot anomaly through time for each site. -->
<!-- site_anomaly <- site.preds.unlisted.anom %>%  -->
<!--   dplyr::group_by(site.id) %>% -->
<!--   tidyr::nest() -->


<!-- int_anom_plot <- function(x) { -->
<!--   ggplot(data = x, -->
<!--          aes(x = date, -->
<!--              y = anom)) + -->
<!--     geom_line(colour = "red", size = 1.0) + -->
<!--     xlab("Year BC/AD") + -->
<!--     ylab("Temperature Anomaly (°C)") + -->
<!--     scale_x_continuous(breaks = seq(-1000, 1800, 200), -->
<!--                        minor_breaks = seq((-1000 + 100), (1800 - 100), 200)) + -->
<!--     # scale_y_continuous(breaks = seq(( -->
<!--     #   DescTools::RoundTo(min(fit$value), multiple = 0.5, FUN = floor) -->
<!--     # ), ( -->
<!--     #   DescTools::RoundTo(max(fit$value), multiple = 0.5, FUN = ceiling) -->
<!--     # ), 0.5)) + -->
<!--     theme_bw() + -->
<!--     theme( -->
<!--       panel.border = element_blank(), -->
<!--       panel.grid.major = element_blank(), -->
<!--       axis.text = element_text( -->
<!--         size = 10, -->
<!--         colour = "black", -->
<!--         family = "Helvetica" -->
<!--       ), -->
<!--       axis.title.y = element_text( -->
<!--         size = 12, -->
<!--         family = "Helvetica", -->
<!--         margin = margin( -->
<!--           t = 10, -->
<!--           r = 20, -->
<!--           b = 10, -->
<!--           l = 10 -->
<!--         ) -->
<!--       ), -->
<!--       axis.title.x = element_text( -->
<!--         size = 12, -->
<!--         family = "Helvetica", -->
<!--         margin = margin( -->
<!--           t = 20, -->
<!--           r = 10, -->
<!--           b = 10, -->
<!--           l = 10 -->
<!--         ) -->
<!--       ), -->
<!--       panel.grid.minor = element_line(colour = "light grey"), -->
<!--       axis.line = element_line(colour = "black"), -->
<!--       legend.text = element_text(size = 10, family = "Helvetica"), -->
<!--       legend.title = element_text(size = 11, family = "Helvetica") -->
<!--     ) -->
<!-- } -->


<!-- plot_objects2 <- purrr::map(site_anomaly$data, int_anom_plot) -->

<!-- ok3 <- purrr::map(plot_objects2, 1)  -->
<!-- ok3 <- lapply(ok3, `[[`, 2) -->
<!-- ok3 <- lapply(ok3, `[`, 1) %>% unlist() -->

<!-- names(plot_objects2) <- c(ok3) -->


<!-- ok2 <- ggpubr::ggarrange(plotlist= plot_objects2, -->
<!--                     labels = c(names(plot_objects2)), -->
<!--                     ncol = 4, nrow = 9, vjust = -0.5) -->

<!-- annotate_figure(ok2, top = text_grob("",  -->
<!--                color = "red", face = "bold", size = 14)) -->

<!-- ``` -->


<!-- ```{r fig1_alt, fig.cap="Modern samples in North America.", echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',fig.keep='all'} -->

<!-- # ggplot(data = usa) + -->
<!-- #   geom_sf(fill = NA) + -->
<!-- #   geom_sf(data = MPCT_final, -->
<!-- #           inherit.aes = FALSE, -->
<!-- #           aes(geometry = geometry)) + -->
<!-- #   coord_sf(xlim = c(-125,-95), ylim = c(25, 50)) + -->
<!-- #   theme_classic() + -->
<!-- #   theme(axis.text = element_text( -->
<!-- #       size = 16, -->
<!-- #       colour = "black", -->
<!-- #       family = "Helvetica" -->
<!-- #     )) -->


<!-- library(tidyverse) -->
<!-- library(rnaturalearth) -->
<!-- library(sf) -->
<!-- library(ggtext) -->

<!-- dat <- MPCT_metadata_counts_final %>%  -->
<!--   dplyr::select(c(dataset.id, geometry, PINUSX)) %>%  -->
<!--   filter(!is.na(PINUSX)) -->

<!-- usa2 <- st_cast(usa, "POLYGON") %>% -->
<!--   mutate(mapcolor7 = sample(1:7, n(), replace = TRUE)) -->


<!-- usa2$fill <- as.factor(usa2$ID) -->
<!-- usa2$fill <- c("#F9D8D6", "#CDF5F6", "#F9EBDF", "#EFD2AC", "#f9d6f7", "#d6f9d8", "#f7f9d6")[usa2$mapcolor7] -->
<!-- usa2$stroke <- 2 -->
<!-- usa2$fillweight <- 4.0 -->

<!-- # MULTIPOLYGON (and also MULTILINESTRING) are not supported -->
<!-- usa2 <- st_cast(usa2, "POLYGON") -->


<!-- dat <- st_sf(dat) -->
<!-- st_crs(dat) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0" -->
<!-- dat$size <- 8 -->
<!-- dat$color <- "#000000" -->
<!-- # dat$label <- cities$name -->
<!-- # dat$label_pos <- "e" -->


<!-- dat1 <- dat -->
<!-- dat1$size <- ambient::normalise((dat1$PINUSX)) -->
<!-- dat1$radius <- dat1$size / 10 -->
<!-- st_crs(dat1) <- st_crs(usa) -->
<!-- dat1$size <- ambient::normalise(dat1$size, to = c(10, 30)) -->
<!-- st_crs(dat1) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0" -->
<!-- dat1$color <- "red" -->


<!-- roughsf_map <- roughsf::roughsf(list(usa2, dat1), -->
<!--                  title = "Modern Pine Pollen Samples across the United States", caption = "*Points are scaled based on the count of pine pollen grains at each site. Data are from the Neotoma Paleoecology Database.", -->
<!--                  title_font = "48px Pristina", font = "30px Pristina", caption_font = "18px Pristina", -->
<!--                  roughness = 1, bowing = 1, simplification = 1, -->
<!--                  width = 1600, height = 1000,  -->
<!-- ) -->

<!-- roughsf::save_roughsf(roughsf_map, "roughsf_map.png") -->


<!-- europe <- ne_countries(scale = 50, continent = "North America", returnclass = "sf") -->

<!-- europe$fill <- as.factor(europe$mapcolor7) -->
<!-- dat$size <- ambient::normalise(log(dat$PINUSX)) -->
<!-- dat$radius <- dat$size / 10 -->

<!-- newloc <- packcircles::circleRepelLayout(select(dat, long, lat, radius)) -->
<!-- dat1 <- bind_cols(dat, newloc$layout[, -3]) -->


<!-- map_title <- "<span style='font-size:32pt;'>Figurative Map of the Cargo Tonnage of the Major Ports of Europe</span>" -->
<!-- p <- ggplot() + -->
<!--   geom_sf(data = europe, aes(fill = fill), show.legend = FALSE, size = 0.1) + -->
<!--   # geom_sf_text( -->
<!--   #   data = europe[europe$pop_est > 8e6 & !europe$name_long %in% c("Netherlands", "Belgium", "Portugal"), ], -->
<!--   #   aes(label = name_long), size = 10, family = "EB Garamond 08" -->
<!--   # ) + -->
<!--   geom_point(data = dat1, aes(x, y, size = I(size)), show.legend = FALSE, shape = 21, fill = "darkgreen") + -->
<!--   geom_text(data = dat1, aes(x, y, size = I(size / 3), label = PINUSX), family = "EB Garamond 08") + -->
<!--   #geom_text(data = dat1, aes(x, y, label = city), size = 2, vjust = -dat$size / 3, family = "EB Garamond 08") + -->
<!--   scale_fill_manual(values = c("#F9D8D6", "#CDF5F6", "#F9EBDF", "#EFD2AC", "#f9d6f7", "#d6f9d8", "#f7f9d6")) + -->
<!--   coord_sf(expand = FALSE, xlim = c(-10, 50), ylim = c(35, 75)) + -->
<!--   # title -->
<!--   annotate("richtext", -->
<!--     x = -Inf, y = Inf, hjust = 0, vjust = 1, label = map_title, -->
<!--     size = 8, fill = "#e8e4c9", family = "EB Garamond 08", -->
<!--     label.padding = unit(c(3.25, 1.0, 3.0, 1.0), "lines") -->
<!--   ) + -->
<!--   # caption -->
<!--   annotate("richtext", -->
<!--     x = Inf, y = -Inf, hjust = 1, vjust = 0, label = "<span style='font-size:22pt'>@schochastics</span>", -->
<!--     size = 12, fill = NA, family = "EB Garamond 08", label.color = NA, -->
<!--     label.padding = unit(c(0.2, 0.2, 0.2, 0.2), "lines") -->
<!--   ) + -->
<!--   theme_void() + -->
<!--   theme( -->
<!--     plot.title = element_text(family = "EB Garamond 08", size = 46, hjust = 0, margin = margin(0, 0, 0, 0)), -->
<!--     plot.background = element_rect(fill = "#e8e4c9", colour = "black", size = 0.5), -->
<!--     panel.background = element_rect(fill = "#e8e4c9", colour = "black", size = 0.1) -->
<!--   ) -->

<!-- ragg::agg_png("13_naturalearth.png", width = 1500, height = 1500) -->
<!-- p -->
<!-- dev.off() -->

<!-- europe <- ne_countries(scale = 110, continent = "North America", returnclass = "sf") -->
<!-- europe$fill <- c("#F9D8D6", "#CDF5F6", "#F9EBDF", "#EFD2AC", "#f9d6f7", "#d6f9d8", "#f7f9d6")[europe$mapcolor7] -->
<!-- europe$fillweight <- 2 -->
<!-- europe$label <- "" -->
<!-- keep <- c("Spain", "Germany", "Poland", "Austria", "Hungary", "Romania") -->
<!-- europe <- st_cast(europe, "POLYGON") -->
<!-- europe_crop <- st_crop(europe, st_polygon(list(matrix(c(-10, 32, 50, 32, 50, 70, -10, 70, -10, 32), ncol = 2, byrow = TRUE)))) -->

<!-- dat1 <- dat1 %>% st_as_sf(coords = c("long", "lat")) -->
<!-- st_crs(dat1) <- st_crs(europe) -->
<!-- dat1$size <- ambient::normalise(dat1$size, to = c(10, 30)) -->
<!-- dat1_crop <- st_crop(dat1, st_polygon(list(matrix(c(-10, 32, 50, 32, 50, 75, -10, 75, -10, 32), ncol = 2, byrow = TRUE)))) %>% -->
<!--   dplyr::filter(y >= 35) -->
<!-- dat1_crop$color <- "red" -->

<!-- water <- data.frame(name = "water") -->
<!-- water$geometry <- st_sfc(st_polygon(list(matrix(c(-10, 32, 50, 32, 50, 73, -10, 73, -10, 32), ncol = 2, byrow = TRUE)))) -->
<!-- water <- st_sf(water) -->
<!-- st_crs(water) <- st_crs(europe) -->
<!-- water$fill <- "#006994" -->
<!-- water$fillstyle <- "cross-hatch" -->
<!-- water$fillweight <- 0.1 -->
<!-- water$stroke <- 5 -->

<!-- europe_bg <- europe_crop -->
<!-- europe_bg$fill <- "#ffffff" -->
<!-- europe_bg$fillstyle <- "solid" -->
<!-- pst <- roughsf::roughsf(list(water, dat1_crop), -->
<!--   title = "Ports of Europe", title_font = "94px Pristina", -->
<!--   caption = "(data from naturalearth) drawn by @schochastics", caption_font = "40px Pristina", -->
<!--   width = 2500, height = 2500 -->
<!-- ) -->
<!-- pst -->
<!-- roughsf::save_roughsf(pst, "13_naturalearth.png") -->

<!-- ``` -->


<!-- ``` -->

<!-- ggplot(data = world) + -->
<!--     geom_sf() + geom_sf(data = MPCT_final, inherit.aes = FALSE, aes(geometry = geometry)) + coord_sf(xlim = c(-125, -95), ylim = c(25, 50)) -->

<!-- ``` -->
