---
title: "Data Visualization for Upland United States Southwest Pollen-based Climate Reconstruction"
author: "Andrew Gillreath-Brown"
date: "5/3/2021"
mainfont: Calibri
output:
  html_document:
    code_folding: show
    keep_md: yes
    number_sections: yes
    theme: sandstone
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
always_allow_html: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# devtools::install()
# devtools::load_all()
devtools::install_github("zeehio/facetscales")
library(paleomat)

```

# Load the final reconstruction data.

```{r load_data, echo = FALSE, message=FALSE, warning=FALSE, results='hide'}

# Load tavg data.
if (file.exists(here::here("vignettes/data/reconst_tavg_final.rds"))) {
  reconst_tavg_final <-
    readr::read_rds(here::here("vignettes/data/reconst_tavg_final.rds"))
} else {
  stop(
    "The final output file for the reconstruction has not been made. Please return to the UUSS_MAT_Reconstruction.RMD to complete the reconstruction."
  )
  
}


```

# Summarize the results.

```{r summarize, echo=FALSE}

# First, convert the years BP in the age column to BC/AD dates, which we create a new column called date.
reconst_tavg_final <- reconst_tavg_final %>% 
  dplyr::mutate(date = paleomat::BPtoBCAD(reconst_tavg_final$age))

# Do 100 year average temperatures across growing season months (May through September).
UUSS_100yrAvgs_tavg_GS <- reconst_tavg_final %>%
  dplyr::filter(month >= 5 & month <= 9) %>%
  dplyr::filter(age < 5950) %>%
  dplyr::group_by(period = cut(date, breaks = seq(-4100, 2100, 100))) %>%
  dplyr::summarise_at(
    c("value", "error", "elev"),
    dplyr::funs(
      mean,
      n = dplyr::n(),
      unique_sites = dplyr::n_distinct(site.id),
      unique_datasets = dplyr::n_distinct(dataset.id)
    )
  ) %>%
  dplyr::arrange(as.numeric(period)) %>%
  dplyr::select(
    -c(
      error_n,
      elev_n,
      error_unique_sites,
      error_unique_datasets,
      elev_unique_sites,
      elev_unique_datasets
    )
  ) %>%
  dplyr::mutate(midP = seq(-3950, 2050, 100))

# Do 100 year average temperatures for the warmest month of the year, July.
UUSS_100yrAvgs_tavg_July <- reconst_tavg_final %>%
  dplyr::filter(month == 7) %>%
  dplyr::filter(age < 5950) %>%
  dplyr::group_by(period = cut(date, breaks = seq(-4100, 2100, 100))) %>%
  dplyr::summarise_at(
    c("value", "error", "elev"),
    dplyr::funs(
      mean,
      n = dplyr::n(),
      unique_sites = dplyr::n_distinct(site.id),
      unique_datasets = dplyr::n_distinct(dataset.id)
    )
  ) %>%
  dplyr::arrange(as.numeric(period)) %>%
  dplyr::select(
    -c(
      error_n,
      elev_n,
      error_unique_sites,
      error_unique_datasets,
      elev_unique_sites,
      elev_unique_datasets
    )
  ) %>%
  dplyr::mutate(midP = seq(-3950, 2050, 100))

#We can also visualize how the number of samples changes through time.
ggplot(UUSS_100yrAvgs_tavg_July,aes(x=midP,y=value_n))+geom_bar(stat="identity")

```

# Plotting the results. 

```{r plot_reconst, fig.width=8, fig.height=9, echo=FALSE}

#Here, we plot temperature for the warmest month, July, through time.
UUSS_100yrAvgs_tavg_GS_plot <-
  ggplot(
    data = (dplyr::filter(UUSS_100yrAvgs_tavg_July[1:60,])),
    aes(
      x = midP,
      y = value_mean,
      label = value_n,
      label2 = value_unique_sites
    )
  ) +
  #scale_color_gradient(low="blue", high="red") +
  geom_ribbon(
    aes(
      x = midP,
      ymin = value_mean - error_mean,
      ymax = value_mean + error_mean,
      alpha = 0.2
    ),
    fill = "grey",
    colour = "dark grey",
    show.legend = F
  ) +
  geom_line(colour = "red", size = 3.0) +
  xlab("Year BC/AD") +
  ylab("Temperature 째C") +
  scale_x_continuous(breaks = seq(-5100, 2100, 200),
                     minor_breaks = seq(-5000, 2000, 200)) +
  scale_y_continuous(breaks = seq(9, 20, 1), limits = c(9, 20)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 18,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  ) +
  labs(col = "Temperature (째C)")

# Save the plot for GS.
ggsave(
  UUSS_100yrAvgs_tavg_GS_plot,
  file = "UUSS_100yrAvg_GrowingSeason_Temperature.pdf",
  path = "vignettes/figures",
  units = "in",
  width = 21,
  height = 13
)


```


# Temperature Anomaly

```{r anomaly, fig.width=8, fig.height=9, echo=FALSE}

# Limit modern sites to a limited area of the UUSS for mean temperature.
# Convert reconstruction data to class sf, then get the spatial extent of the fossil pollen sites.
xys <- sf::st_as_sf(reconst_tavg_final) %>%
  raster::extent()

# Create a bounding box for the extent of the fossil pollen sites.
bb2 <-
  c(
    "xmin" = xys[1],
    "xmax" = xys[2],
    "ymin" = xys[3],
    "ymax" = xys[4]
  ) %>%
  sf::st_bbox() %>%
  sf::st_as_sfc() %>%
  sf::st_as_sf(crs = 4326) %>%
  sf::st_transform(crs = 4326)

# Do an intersection and keep only the modern sites that are within the extent of the fossil pollen sites.
UUSS_modern <- sf::st_intersection(MPCT_final, bb2)
UUSS_modern2 <- UUSS_modern[!duplicated(UUSS_modern$geometry),] %>%
  dplyr::select(-pollen) %>%
  tidyr::unnest_longer(climate) %>%
  as.data.frame()
UUSS_modern2$climate <- UUSS_modern2$climate %>%
  dplyr::select(-dplyr::contains(c("ppt", "gdd")))
UUSS_modern2$climate <- UUSS_modern2$climate %>%
  dplyr::select(-c(1:4, 10:12))

# Get mean temperature for prism data for the July.
warmest.month <- as.list(UUSS_modern2$climate[3])
warmest.month <- as.numeric(as.vector(warmest.month$tavg_7))
warmest.month <- mean(warmest.month)

July_anom <- UUSS_100yrAvgs_tavg_July %>%
  dplyr::mutate(anom =  value_mean - warmest.month)

# Get the top of the fossil cores reconstructed values that fall within 1961-1990. This is for a potential anomaly baseline adjustment. Would take same sites modern samples and see how the average differs from the reconstructed samples. 
# reconst_tavg_final %>% 
#   dplyr::filter(age < -12 & month == 7 & sample.id %in% c(192202, 347871, 186185, 136827, 192408, 132358, 142897, 154412)) %>% 
#   dplyr::select(value) %>% 
#   colMeans()

# July.recon.mean <- mean(UUSS_100yrAvgs_tavg_July$value_mean)
# July_anom2 <- UUSS_100yrAvgs_tavg_July %>%
#   dplyr::mutate(anom =  value_mean - July.recon.mean)
# July_anom3 <- reconst_tavg_final %>%
#      dplyr::filter(month == 7) %>%
#      dplyr::filter(age < 5950)
# July_anom3 <- mean(July_anom3$value)

UUSS_100yrAvgs_tavg_anom <-
  ggplot(
    data = (dplyr::filter(anom)),
    aes(
      x = name,
      y = value
    )
  ) +
  geom_line(colour = "red", size = 3.0) +
  xlab("Year BC/AD") +
  ylab("Temperature Anomaly") +
  scale_x_continuous(breaks = seq(-3100, 2100, 200),
                     minor_breaks = seq(-3000, 2000, 200)) +
  #scale_y_continuous(breaks = seq(-4, 4, 1), limits = c(-4, 4)) +
  #geom_smooth() +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 18,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  ) +
  labs(col = "Temperature (째C)") 

# Save the plot for GS.
ggsave(
  UUSS_100yrAvgs_tavg_anom,
  file = "UUSS_100yrAvgs_tavg_anom.pdf",
  path = "vignettes/figures",
  units = "in",
  width = 21,
  height = 13
)


# Temperature anomaly for growing season months.
# Get mean temperature for prism data for the growing season (May to September).
gs.months <- unlist(UUSS_modern2$climate, use.names = FALSE)
gs.months <- mean(gs.months)

gs_anom <- UUSS_100yrAvgs_tavg_GS %>%
  dplyr::mutate(anom =  value_mean - gs.months)




UUSS_100yrAvgs_tgs_anom <-
  ggplot(
    data = (dplyr::filter(gs_anom[44:60,])),
    aes(
      x = midP,
      y = anom,
      label = value_n,
      label2 = value_unique_sites
    )
  ) +
  geom_line(colour = "red", size = 3.0) +
  xlab("Year BC/AD") +
  ylab("Temperature Anomaly") +
  scale_x_continuous(breaks = seq(300, 2100, 200),
                     minor_breaks = seq(400, 2000, 200)) +
  scale_y_continuous(breaks = seq(-4, 4, 1), limits = c(-4, 4)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 18,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 28,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  ) +
  labs(col = "Temperature (째C)")



# writeRaster(PRISM_tavg_monthly_normals, filename="/Users/andrew/Dropbox/WSU/SKOPEII/Figures/PRISM_tavg_monthly_normals.tif", format="GTiff", overwrite=TRUE)
# Get tavg PRISM raster for July.
July_PRISM_tavg <- brick("/Users/andrew/Dropbox/WSU/SKOPEII/Figures/PRISM_tavg_monthly_normals.tif") %>% 
  raster::subset(7)

```


```{r anomaly_2, fig.width=8, fig.height=9, echo=FALSE}

# Method 1: Use temporal interpolations from all sites to create overall reconstruction.
tavg_100yrs_all <- tavg_predicted %>%
  dplyr::select(-model_fit,-plot_fit) %>%
  tidyr::unnest(mean_100yrs)

# Here, we set up the midpoint years of each century from the minimum to maximum year represented by each site.
agemax <- max(tavg_100yrs_all$date)
agemax_rounded <- agemax %>%
  DescTools::RoundTo(multiple = 100, FUN = ceiling)
agemin <- min(tavg_100yrs_all$date)
agemin_rounded <- agemin %>%
  DescTools::RoundTo(multiple = 100, FUN = floor)

predict.points <-
  as.data.frame(seq((agemin_rounded + 50), (agemax_rounded - 50), by = 100))
names(predict.points)[1] <- "date"

# GAM
model_gam <-
  mgcv::gam(anom ~ s(date, bs = "cp", k = 32),
            data = tavg_100yrs_all,
            family = gaussian())
plot(model_gam)
gam_knots <-
  model_fit$smooth[[1]]$xp  ## extract knots locations
# Can also get more basic data for plot by saving the plot.gam as an object. Then, could save something like the standard error.
plot_gam <- plot.gam(model_gam)
plot_gam[[1]]$se

predict.points <- as.data.frame(predict.points) %>%
  dplyr::rename(date = predict.points)

predict.anom <-
  as.data.frame(mgcv::predict.gam(model_gam,
                                  predict.points,
                                  type = 'response',
                                  se.fit = TRUE)) %>%
  dplyr::rename(anom = 1)

fit <- cbind(predict.points, predict.anom)

fit <- fit %>%
  dplyr::filter(date >= -1000 & date <= 1799)

plot_gam <- ggplot(data = fit,
                   aes(x = date,
                       y = anom)) +
  # geom_ribbon(
  #   data = fit,
  #   aes(
  #     x = date,
  #     ymin = anom - 1.96 *  se.fit,
  #     ymax = anom + 1.96 * se.fit,
  #     alpha = 0.2
  #   ),
  #   fill = "grey",
  #   colour = "dark grey",
  #   show.legend = F
# ) +
geom_line(colour = "red", size = 1.0) +
  # geom_point(data = eliminated, aes(x = date,
  #                                   y = anom)) +
  xlab("Year BC/AD") +
  ylab("Temperature Anomaly") +
  scale_x_continuous(
    breaks = seq(agemin_rounded, agemax_rounded, 200),
    minor_breaks = seq((agemin_rounded + 100), (agemax_rounded -
                                                  100), 200)
  ) +
  scale_y_continuous(breaks = seq(-2.0, 2.0, 0.1), limits = c(-1.0, 0)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 14,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )

#TPS
predict.points <- as.numeric(unlist(predict.points))
smooth.dim <-
  length(predict.points) #ceiling(length(tavg_100yrs_all$anom) * 0.3)

model_tps <-
  fields::Tps(tavg_100yrs_all$date, tavg_100yrs_all$anom, df = smooth.dim)

fhat <- predict(model_tps, predict.points)

# se.fit.avg <- tavg_100yrs_all %>% 
#   dplyr::ungroup() %>% 
#   dplyr::select(date, se.fit) %>%
#   dplyr::group_by(date) %>% 
#   dplyr::summarise(se.avg = mean(se.fit, na.rm = TRUE))
  

fit <-
  cbind(as.data.frame(predict.points) %>% dplyr::rename(date = predict.points),
        as.data.frame(fhat) %>% dplyr::rename(anom = V1)) #%>% 
  #dplyr::left_join(se.fit.avg, by = "date")
#names(fit) <- c("date", "anom", "se.fit")

fit <- fit %>%
  dplyr::filter(date >= -1000 & date <= 1799)

plot_tps <- ggplot(data = fit,
                   aes(x = date,
                       y = anom)) +
# geom_ribbon(
#   data = fit,
#   aes(
#     x = date,
#     ymin = anom - 1.96 *  se.avg,
#     ymax = anom + 1.96 * se.avg,
#     alpha = 0.2
#   ),
#   fill = "grey",
#   colour = "dark grey",
#   show.legend = F
# ) +
geom_line(colour = "red", size = 1.0) +
  # geom_point(data = eliminated, aes(x = date,
  #                                   y = anom)) +
  xlab("Year BC/AD") +
  ylab("Temperature Anomaly") +
  scale_x_continuous(
    breaks = seq(agemin_rounded, agemax_rounded, 200),
    minor_breaks = seq((agemin_rounded + 100), (agemax_rounded -
                                                  100), 200)
  ) +
  scale_y_continuous(breaks = seq(-1.5, 1.0, 0.5),
                     limits = c(-1.5, 1.0)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 14,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )

smooth_vals = predict(fit)
garb3$smooth_vals <- smooth_vals

# Animate
plot_tps <- ggplot(data = fit,
                   aes(x = date,
                       y = anom)) +
geom_line(colour = "red", size = 1.0, aes(y = anom)) +
    transition_reveal(date) +
  ease_aes("linear") +
  xlab("Year BC/AD") +
  ylab("Temperature Anomaly") +
  scale_x_continuous(
    breaks = seq(agemin_rounded, agemax_rounded, 200),
    minor_breaks = seq((agemin_rounded + 100), (agemax_rounded -
                                                  100), 200)
  ) +
  scale_y_continuous(breaks = seq(-1.5, 1.0, 0.5),
                     limits = c(-1.5, 1.0)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 10,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )

anim2 <- animate(plot_tps, fps = 10, duration = 7, height = 4, width = 7, units = "in", res = 300)
anim_save(animation = anim2, filename ="/Users/andrew/Dropbox/WSU/SKOPEII/Figures/anomaly.gif")


#******************************








# Method 2: Use pre-temporal interpolations from all sites to create overall reconstruction.
tavg_all <- tavg

# Here, we set up the midpoint years of each century from the minimum to maximum year represented by each site.
agemax <- max(tavg_all$date)
agemax_rounded <- agemax %>%
  DescTools::RoundTo(multiple = 100, FUN = ceiling)
agemin <- min(tavg_all$date)
agemin_rounded <- agemin %>%
  DescTools::RoundTo(multiple = 100, FUN = floor)

predict.points <-
  as.data.frame(seq((agemin_rounded + 50), (agemax_rounded - 50), by = 100))
names(predict.points)[1] <- "date"

# GAM
model_gam <-
  mgcv::gam(anom ~ s(date, bs = "cp", k = 32),
            data = tavg_all,
            family = gaussian())
plot(model_gam)
gam_knots <-
  model_fit$smooth[[1]]$xp  ## extract knots locations
# Can also get more basic data for plot by saving the plot.gam as an object. Then, could save something like the standard error.
plot_gam <- plot.gam(model_gam)
plot_gam[[1]]$se

predict.points <- as.data.frame(predict.points) %>%
  dplyr::rename(date = predict.points)

predict.anom <-
  as.data.frame(mgcv::predict.gam(model_gam,
                                  predict.points,
                                  type = 'response',
                                  se.fit = TRUE)) %>%
  dplyr::rename(anom = 1)

fit <- cbind(predict.points, predict.anom)

fit <- fit %>%
  dplyr::filter(date >= -1000 & date <= 1799)

plot_gam <- ggplot(data = fit,
                   aes(x = date,
                       y = anom)) +
  # geom_ribbon(
  #   data = fit,
  #   aes(
  #     x = date,
  #     ymin = anom - 1.96 *  se.fit,
  #     ymax = anom + 1.96 * se.fit,
  #     alpha = 0.2
  #   ),
  #   fill = "grey",
  #   colour = "dark grey",
  #   show.legend = F
# ) +
geom_line(colour = "red", size = 1.0) +
  # geom_point(data = eliminated, aes(x = date,
  #                                   y = anom)) +
  xlab("Year BC/AD") +
  ylab("Temperature Anomaly") +
  scale_x_continuous(
    breaks = seq(agemin_rounded, agemax_rounded, 200),
    minor_breaks = seq((agemin_rounded + 100), (agemax_rounded -
                                                  100), 200)
  ) +
  scale_y_continuous(breaks = seq(-2.0, 2.0, 0.5), limits = c(-2.0, 0)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 14,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )

#TPS
predict.points <- as.numeric(unlist(predict.points))
smooth.dim <-
  length(predict.points) #ceiling(length(tavg_all$anom) * 0.3)

model_tps <-
  fields::Tps(tavg_all$date, tavg_all$anom, df = 32)

fhat <- predict(model_tps, predict.points)

SE <- fields::predictSE(model_tps, predict.points)

fit <-
  cbind(as.data.frame(predict.points),
        as.data.frame(fhat),
        as.data.frame(SE))
names(fit) <- c("date", "anom", "se.fit")

fit <- fit %>%
  dplyr::filter(date >= -1000 & date <= 1799)

plot_tps <- ggplot(data = fit,
                   aes(x = date,
                       y = anom)) +
  # geom_ribbon(
  #   data = fit,
  #   aes(
  #     x = date,
  #     ymin = anom - 1.96 *  se.fit,
  #     ymax = anom + 1.96 * se.fit,
  #     alpha = 0.2
  #   ),
  #   fill = "grey",
  #   colour = "dark grey",
  #   show.legend = F
# ) +
geom_line(colour = "red", size = 1.0) +
  # geom_point(data = eliminated, aes(x = date,
  #                                   y = anom)) +
  xlab("Year BC/AD") +
  ylab("Temperature Anomaly") +
  scale_x_continuous(
    breaks = seq(agemin_rounded, agemax_rounded, 200),
    minor_breaks = seq((agemin_rounded + 100), (agemax_rounded -
                                                  100), 200)
  ) +
  scale_y_continuous(breaks = seq(-2.0, 0, 0.5),
                     limits = c(-2.0, 0.0)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 14,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )


```


```{r elevation_anomaly, fig.width=8, fig.height=9, echo=FALSE}

ok6 <- tavg_100yrs %>%
  dplyr::mutate(elev_avg = purrr::map(site.predictions, .f = function(x) {
    mean(x$elev)
  })) %>% 
  dplyr::mutate(anom_avg = purrr::map(site.predictions, .f = function(x) {
    mean(x$anom)
  })) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(-site.predictions, -date) %>% 
  tidyr::unnest(cols = c(elev_avg, anom_avg)) %>% 
  as.data.frame()

```




```{r maize, fig.width=8, fig.height=9, echo=FALSE}

#/Users/andrewgillreath-brown/Dropbox/WSU/
MDB_nest <-
  readRDS(
    "/Users/andrewgillreath-brown/Dropbox/WSU/Dissertation/Paper 1/Maize compilation/MDB_full_cal_min.RDS"
  ) %>%
  dplyr::mutate(date = paleomat::BPtoBCAD(MedianBP)) %>%
  dplyr::filter(date >= -1000 & date <= 900) %>%
  dplyr::mutate(date = (DescTools::RoundTo(
    date, multiple = 100, FUN = floor
  ) + 50)) %>%
  dplyr::select(Longitude, Latitude, Lab_code, Site_name, Elevation_masl, date) %>%
  mutate_at(c("Longitude", "Elevation_masl"), ~ as.numeric(as.character(.))) %>%
  dplyr::filter(Latitude >= 31.334 &
                  Latitude <= 38.09 & Longitude < -104.00) %>%
  dplyr::group_by(date) %>%
  tidyr::nest() %>%
  dplyr::arrange(date)
  
  MDB <- purrr::map(
    MDB_nest$data,
    .f = function(x) {
      sp::SpatialPointsDataFrame(x[,1:2], 
                                 x,
                   proj4string = CRS("+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0"))
    }
  )
names(MDB) <- c("BC950","BC850","BC750", "BC650", "BC550","BC450", "BC350", "BC250", "BC150", "BC50", "AD50", "AD150", "AD250", "AD350", "AD450")




MDB_NF <- readRDS("/Users/andrew/Dropbox/WSU/Dissertation/Paper 1/Maize compilation/MDB_north_frontier.RDS")
MDB_NF$MedianBP <- as.numeric(MDB_NF$MedianBP)
MDB_NF <- MDB_NF %>% 
  dplyr::mutate(date = paleomat::BPtoBCAD(MedianBP))
MDB_NF$date[[8]] <- MDB_NF$date[[8]]+1
MDB_NF$date[[9]] <- MDB_NF$date[[9]]+15
MDB_NF$date[[12]] <- MDB_NF$date[[12]]+1

```


```{r anomaly_maize_plot, fig.width=8, fig.height=9, echo=FALSE}

# Prepare Maize plot.
# "/Users/andrewgillreath-brown/Dropbox/WSU/SKOPEII/Figures/"
MDB_FULL<-
  readRDS(
    "/Users/andrew/Dropbox/WSU/Dissertation/Paper 1/Maize compilation/MDB_full_cal_min.RDS"
  ) %>%
  dplyr::mutate(date = paleomat::BPtoBCAD(MedianBP)) %>%
  dplyr::filter(date >= -1000 & date <= 1800) %>%
  dplyr::mutate(date = (DescTools::RoundTo(
    date, multiple = 100, FUN = floor
  ) + 50)) %>%
  dplyr::select(Longitude, Latitude, Lab_code, Site_name, Elevation_masl, date) %>%
  mutate_at(c("Longitude", "Elevation_masl"), ~ as.numeric(as.character(.))) %>%
  dplyr::filter(Latitude >= 31.334 &
                  Latitude <= 38.09 & Longitude < -104.00)

maize_plot <- ggplot(MDB_FULL, aes(x = date, y = Latitude)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red", formula = y ~ x) +
    xlab("Year BC/AD") +
  ylab("Latitude") +
  scale_x_continuous(
    breaks = seq(-1000, 1400, 200),
    minor_breaks = seq((-1000 + 100), (1400 -
                                                  100), 200)
  ) +
  scale_y_continuous(breaks = seq(31.5, 38, 0.5)) +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 14,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )


# Use faceting to plot together.
t1 <- fit %>% 
  dplyr::select(date, anom) %>%
  reshape2::melt(measure.vars = c("anom")) %>% 
  dplyr::mutate(variable = "Anomaly")
t2 <- MDB_FULL %>% 
  dplyr::select(date, Latitude) %>% 
  reshape2::melt(measure.vars = c("Latitude"))
multi.plot <- rbind(t1, t2)

scales_y <- list(
  `Anomaly` = scale_y_continuous(limits = c(-1.5, 0.5), breaks = seq(-1.5, 0.5, 0.25)),
  `Latitude` = scale_y_continuous(limits = c(31.5, 37.5), breaks = seq(31.5, 37.5, 0.5))
)

ggplot(multi.plot, mapping = aes(x = date, y = value)) +
  facet_grid(variable ~ ., scales = "free_y") +
  geom_line(data = t1, stat = "identity") + 
  geom_point(data = t2, stat = "identity") +
  stat_smooth(data = t2, method = "lm", col = "red", formula = y ~ x) +
  xlab("Year BC/AD") +
  ylab("Value") +
  scale_x_continuous(
    breaks = seq(-1000, 2000, 200),
    minor_breaks = seq((-1000 + 100), (2000 -100), 200)
  ) +
  facetscales::facet_grid_sc(rows = vars(variable), 
                scales = list(y = scales_y)) +
  #scale_y_continuous(breaks = seq(31.5, 38, 0.5)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    axis.text = element_text(
      size = 14,
      colour = "black",
      family = "Helvetica"
    ),
    axis.title.y = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 10,
        r = 20,
        b = 10,
        l = 10
      )
    ),
    axis.title.x = element_text(
      size = 20,
      family = "Helvetica",
      margin = margin(
        t = 20,
        r = 10,
        b = 10,
        l = 10
      )
    ),
    panel.grid.minor = element_line(colour = "light grey"),
    axis.line = element_line(colour = "black"),
    legend.text = element_text(size = 18, family = "Helvetica"),
    legend.title = element_text(size = 22, family = "Helvetica")
  )



```



```{r anomaly_maize_maps, fig.width=8, fig.height=9, echo=FALSE}

#First, get reconstruction data, then limit to the maize range (BC950 to AD450).
tavg_recon <- purrr::map(tavg_preds, 1)
names(tavg_recon) <- c("BC950","BC850","BC750", "BC650", "BC550","BC450", "BC350", "BC250", "BC150", "BC50", "AD50", "AD150", "AD250", "AD350", "AD450", "AD550", "AD650", "AD750", "AD850","AD950", "AD1050", "AD1150", "AD1250", "AD1350", "AD1450", "AD1550", "AD1650", "AD1750")
tavg_recon <- tavg_recon[1:15]

# Get maize database and change all time periods to sf objects.
MDB_sf <- MDB %>%
  purrr::map(
    .f = function(x) {
      sf::st_as_sf(x, crs = 4326)
    }
  )

# Get major cities in US (will limit these in the function used below).
data(us.cities)

# Need to put the temp and maize data into one list in order to run map on it. First, I make each time period a list of a list (to make it easier for combining the lists).
tavg_recon_list <- purrr::map(
  tavg_recon,
  .f = function(x) {
    list(x)
  }
)

MDB_sf_list <- purrr::map(
  MDB_sf,
  .f = function(x) {
    list(x)
  }
)

tavg_MDB_list <- 
  mapply(c, tavg_recon_list, MDB_sf_list, SIMPLIFY = FALSE, USE.NAMES = TRUE)

maize_anomaly_plots <-
  purrr::map2(
    .x = tavg_MDB_list, .y = names(tavg_MDB_list),
    .f = function(x, y) {
      plot_map_anomaly_maize(x = x, x.name = y, us.cities = us.cities, animation = FALSE)
    }
  )

# Arrange all of the plots, then can output below as PDF.
maize_anomaly_plots_arranged <- gridExtra::marrangeGrob(maize_anomaly_plots, nrow=2, ncol=1, top=NULL)

# Save as one pdf. Use scale here in order for the multi-plots to fit on each page.
ggsave("/Users/andrewgillreath-brown/Dropbox/WSU/SKOPEII/Figures/maize_anomaly_plots_arranged.pdf", maize_anomaly_plots_arranged, scale = 1.5, 
       width = 210, 
       height = 297, 
       units = "mm")

#Gif animation
## list file names and read in
imgs <- list.files("/Users/andrewgillreath-brown/Dropbox/WSU/SKOPEII/Figures/animation/", full.names = TRUE)
index = c(15, 14, 13, 12, 11, 9, 8, 7, 6, 10, 5, 1, 2, 3, 4)
index = c(4, 3, 2, 1, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
imgs = imgs[order(index)]
img_list <- lapply(imgs, magick::image_read)

## join the images together
img_joined <- image_join(img_list)

## animate at 2 frames per second
img_animated <- image_animate(img_joined, fps = 2)

## view animated image
img_animated

## save to disk
image_write(image = img_animated,
            path = "/Users/andrewgillreath-brown/Dropbox/WSU/SKOPEII/Figures/animation/maize_anomaly_plots_arranged.gif")

```
